name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*

  pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

            fail-fast: false

        name: PHP ${{ matrix.php }} tests
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: json, mbstring, tokenizer, sqlite3
                  coverage: none

            - run: composer install --no-interaction
            - run: vendor/bin/tester tests -s -C
            - if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: output
                  path: tests/**/output

    code-checker:
        name: Code Standard Checker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  coverage: none

            - run: composer create-project nette/code-checker temp/code-checker ^3.2 --no-progress
            - run: php tools/code-checker.php

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

            fail-fast: false

        name: PHP ${{ matrix.php }} PHPStan
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - run: composer install --no-interaction
            - run: composer phpstan -- --no-progress
